import type { Metadata } from "next";
import { cookies } from "next/headers";

import "@ant-design/v5-patch-for-react-19";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider, App } from "antd";

import "./globals.css";
import AppProvider from "@/app/AppProvider";
import { CartProvider } from "@/app/store/CartContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const sessionToken = cookieStore.get("sessionToken");

  return (
    <html lang="en">
      <body>
        <ConfigProvider
          theme={{
            token: { colorPrimary: "#228be6" },
            components: {
              Card: {
                bodyPadding: 15,
              },
            },
          }}
          wave={{ disabled: true }}
        >
          <AntdRegistry>
            <CartProvider>
              <AppProvider initialSessionToken={sessionToken?.value}>
                <App>{children}</App>
              </AppProvider>
            </CartProvider>
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
