server:
  port: 8080
  servlet:
    context-path: /ecommerce

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/ecommerce"
    username: root
    password: 43danang211
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true