server:
  port: 8080
  servlet:
    context-path: /ecommerce

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/ecommerce"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 43danang211
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

jwt:
  signerKey: "hSnod7XmzrPT5oCRwd24a/p57vjAMTJfhXK9LnMdrpo+Wv2N1rlvjbhKebGiF/Ng"

cloudinary:
  cloud-name: "dm1ozebjy"
  api-key: "779548677416465"
  api-secret: "ufoJ9hprJyLxZNZ114Mo_fexvJ0"