import type { Metadata } from "next";
import "@ant-design/v5-patch-for-react-19";

import Header from "@/app/components/Header/Header";
import Footer from "@/app/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    // <body>
    <>
      <Header />
      {children}
      <Footer />
    </>
    // </body>
    // </html>
  );
}
